silo-core: fix order of hook before call for borrow
silo-finance/silo-contracts-v2 pull request #845
Opened 2024-11-27 05:15 UTC by 0xNeoRacer

> Description: Many of the Actions inside Action.sol follow the following pattern:
> 1. Check requirements.
> 2. Hook before the call.
> 3. Turn on the reentrancy guard.

Note: there is only borrow action, not "many of actions".

> This pattern can be used to fully drain a silo given a hook configuration that allows re-entrency, for example, a hook that transfers an unrelated erc777 token would be exploitable with this attack.,

**Fixed** by changing order of hook call.
Fixes: SILO-3253

2024-11-27 11:22 UTC, IhorSF approved these changes

2024-11-28 10:47 UTC, shadowyedd requested changes
This PR should address all places where this pattern is used and can be fixed. We should also add a test for calling borrow of the other asset from hook so `hasDebtInOtherSilo` can revert.

2024-11-29 15:03 UTC, 0xNeoRacer commented
> This PR should address all places where this pattern is used and can be fixed. We should also add a test for calling borrow of the other asset from hook so `hasDebtInOtherSilo` can revert.

done

2024-11-29 20:14 UTC, shadowyedd approved these changes

2024-12-02 06:55 UTC, merged